#!/usr/bin/env node

const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const CONFIG_PATH = path.join(ROOT, 'projects.json');
const DRAFTS_DIR = path.join(ROOT, 'drafts');

function loadConfig() {
  if (!fs.existsSync(CONFIG_PATH)) {
    console.error('Error: projects.json not found');
    process.exit(1);
  }

  const raw = fs.readFileSync(CONFIG_PATH, 'utf8');
  const config = JSON.parse(raw);

  if (!config.projects || !Array.isArray(config.projects)) {
    console.error('Error: projects.json must have a "projects" array');
    process.exit(1);
  }

  return config;
}

function isGitRepo(dir) {
  const gitDir = path.join(dir, '.git');
  return fs.existsSync(gitDir);
}

function getCommits(repoPath, daysBack) {
  const since = `${daysBack} days ago`;
  const format = '%h|%ad|%s|%b|--COMMIT_END--';
  const dateFormat = '%Y-%m-%d';

  try {
    const logOutput = execFileSync('git', [
      'log',
      `--since=${since}`,
      `--date=format:${dateFormat}`,
      `--pretty=format:${format}`
    ], { cwd: repoPath, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] });

    if (!logOutput.trim()) {
      return [];
    }

    const commits = [];
    const rawCommits = logOutput.split('--COMMIT_END--').filter(c => c.trim());

    for (const raw of rawCommits) {
      const parts = raw.trim().split('|');
      if (parts.length < 3) continue;

      const hash = parts[0];
      const date = parts[1];
      const subject = parts[2];
      const body = parts.slice(3).join('|').replace(/\|+$/, '').trim();

      commits.push({ hash, date, subject, body });
    }

    // Get files changed for each commit
    for (const commit of commits) {
      try {
        const files = execFileSync('git', [
          'show',
          '--name-only',
          '--pretty=format:',
          commit.hash
        ], { cwd: repoPath, encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] });
        commit.files = files.trim().split('\n').filter(f => f.trim());
      } catch {
        commit.files = [];
      }
    }

    return commits;
  } catch (err) {
    // No commits in range or other git error
    return [];
  }
}

function formatDate(date) {
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
                  'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  return `${months[date.getMonth()]} ${date.getDate()}, ${date.getFullYear()}`;
}

function generateMarkdown(projectsData, daysBack) {
  const now = new Date();
  const start = new Date(now);
  start.setDate(start.getDate() - daysBack);

  let md = `# Commits: ${formatDate(start)} - ${formatDate(now)}\n\n`;

  let hasContent = false;

  for (const { name, commits } of projectsData) {
    if (commits.length === 0) continue;

    hasContent = true;
    md += `## ${name}\n\n`;

    const allFiles = new Set();

    for (const commit of commits) {
      md += `- \`${commit.hash}\` | ${commit.date} | ${commit.subject}\n`;

      if (commit.body) {
        // Indent body text
        const bodyLines = commit.body.split('\n').filter(l => l.trim());
        for (const line of bodyLines) {
          md += `  ${line}\n`;
        }
      }

      commit.files.forEach(f => allFiles.add(f));
    }

    if (allFiles.size > 0) {
      md += `\nFiles changed: ${Array.from(allFiles).join(', ')}\n`;
    }

    md += '\n';
  }

  if (!hasContent) {
    md += '*No commits found in the specified time range.*\n\n';
  }

  md += `---\n*Generated by YOTB changelog script*\n`;

  return md;
}

function main() {
  const config = loadConfig();
  const { projects, daysBack = 7 } = config;

  if (projects.length === 0) {
    console.log('No projects configured in projects.json');
    console.log('Add project paths to the "projects" array to get started.');
    process.exit(0);
  }

  // Ensure drafts directory exists
  if (!fs.existsSync(DRAFTS_DIR)) {
    fs.mkdirSync(DRAFTS_DIR, { recursive: true });
  }

  const projectsData = [];

  for (const project of projects) {
    const repoPath = project.path.startsWith('/')
      ? project.path
      : path.resolve(ROOT, project.path);

    if (!fs.existsSync(repoPath)) {
      console.warn(`Skipping ${project.name}: path does not exist (${repoPath})`);
      continue;
    }

    if (!isGitRepo(repoPath)) {
      console.warn(`Skipping ${project.name}: not a git repository (${repoPath})`);
      continue;
    }

    const commits = getCommits(repoPath, daysBack);
    console.log(`${project.name}: ${commits.length} commits`);

    projectsData.push({
      name: project.name,
      commits
    });
  }

  const markdown = generateMarkdown(projectsData, daysBack);

  // Output filename with today's date
  const today = new Date().toISOString().split('T')[0];
  const outputPath = path.join(DRAFTS_DIR, `commits-${today}.md`);

  fs.writeFileSync(outputPath, markdown);
  console.log(`\nWritten to: ${outputPath}`);
}

main();
